# Generated by Django 5.0.7 on 2024-08-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_review_content_review_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
